### ISSUE TITLE
Data set not available?

### ISSUE THREAD

**Issue by LenaLawless** [ghostery/whotracks.me#218]
Hey there, i was looking for the data set of whotracks.me for a research for my uni but instead of the data i get this text: 

version https://git-lfs.github.com/spec/v1
oid sha256:42f43921beed49e843db30eeeec308209e71669c4a3c650f101fc35596063519
size 219147

On Wednesday it was still available...  Could you help me with that issue? 

Thanks and greetings 
Lena

**Comment by philipp-classen** [comment]
We did not have any changes since last Wednesday. The last change was around 12th of November.

```
git log --all -p -S 42f43921beed49e843db30eeeec308209e71669c4a3c650f101fc35596063519
```

Points to file `whotracksme/data/assets/2018-06/eu/companies.csv` (commited Tue Aug 28 15:51:29 2018).

Probably, the download aborted for you at some point. At least, that would be consistent with the error that I now got when trying to download it from scratch: 

 ```
git clone git@github.com:ghostery/whotracks.me.git
Cloning into 'whotracks.me'...
...
Receiving objects: 100% (16751/16751), 686.46 MiB | 6.90 MiB/s, done.
Resolving deltas: 100% (7209/7209), done.
Downloading static/img/blog/autoconsent/cookie-blocker-after.gif (12 MB)
Error downloading object: static/img/blog/autoconsent/cookie-blocker-after.gif (ddba742): Smudge error: Error downloading static/img/blog/autoconsent/cookie-blocker-after.gif (ddba742eb728b4cd59fbd5b1ca7f136f68b9d5f298511cc96e238275f0c545da):
batch response: This repository is over its data quota.
Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

So, looks like we exceeded the bandwidth.

**Comment by philipp-classen** [comment]
@LenaLawless  We increased the quota now. You should be able to get the data again.

**Comment by LenaLawless** [comment]
Thanks a lot! It works again and I'll download it directly.




Philipp Claßen <notifications@github.com> schrieb am Mo., 23. Nov. 2020,
12:06:
